import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ShoppingCart } from "lucide-react";
import { ActiveLink } from "./UI/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "ecommerce",
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="mx-auto mt-2 flex max-w-xl  space-x-4">
						<li>
							<ActiveLink href="/">Homepage</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products">All</ActiveLink>
						</li>
						{/* <li>
							<ActiveLink href="/tshirts">T-Shirts</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/hoodies">Hoodies</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/accesories">Accesories</ActiveLink>
						</li> */}
						<ShoppingCart />
					</ul>
				</nav>
				<section className="lg: mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
					{children}
				</section>
				<footer>
					<div className="flex flex-col items-center">
						<ActiveLink href="/privacy-policy">Privacy Policy</ActiveLink>
						<ActiveLink href="/terms-and-conditions">
							Terms and Conditions
						</ActiveLink>
					</div>
					<p className="text-center text-sm text-gray-500">© 2023</p>
				</footer>
			</body>
		</html>
	);
}
